---
title: "Research & Professional"
subtitle: "Research Statement"
format: 
  html: 
    toc: true
    html-math-method: katex
    css: style.css
---

## Research and Professional Experiences

******************************
**RESEARCH**


+ ***Research Group Director*** \| Decision-Making and Analytics Pioneers (D-MAP) Research Group \| CSUEB, School of Engineering \| **Aug 2025 - Present** \|

+ ***Research Associate*** \| Energy, Environment, and Economics Decision-Making Lab \| UMass Amherst \| **Sept 2019 - Dec 2024** \|

    Doctoral Dissertation document: [*"Learning from the past to inform future actions: Learning curve innovations"*](https://scholarworks.umass.edu/entities/publication/947c461c-e52d-4b89-a49b-cd08199958ac) \|Faculty Advisor: Erin D Baker, Distinguished Professor of Industrial Engineering and Operations Research

+ ***Research Assistant*** \| Engineering Economics and Cost Optimization (E2CO) Research Group \| UPR-Mayaguez \| **Aug 2016 – Jun 2018** \|

+ **Patent Research Analyst** \| Intellectual Property and Technology Transfer Office \| UPR-Mayaguez \| **Jan 2017 –June 2017** \|

    Research Contribution: *Intellectual property analysis of projects developed by capstone students related to improve the quality of adults’ life with disabilities. The work included the literature review required to determine whether to apply for projects patents.


+ ***Research Assistant*** \| Engineering Sciences and Materials Department \|  UPR-Mayaguez \| **Jan 2016 – Dec 2016** \|

    Research Project Contribution: Leveraging simulation tools to deliver III structured problems: Enhancing student problem solving ability in static and mechanics of materials.Emphasis: Engineering Education , Faculty Mentor: Dr. Aidsa I. Santiago-Roman


+ ***Research Assistant*** \| Engineering Sciences and Materials Department \| UPR-Mayaguez \| **Jan 2014 – May 2015** \|

    Research Project: *Analysis of common misconceptions of Static concepts among Hispanic Civil and Mechanical Engineering students at UPRM* \| Emphasis: *Engineering Education* \| Faculty Mentor: *Dr. Aidsa I. Santiago-Roman* \| 
    Contributions:  *Conducted interviews with experimental and control students; transcribed the interviews for a better qualitative analysis to identify students’ misconception. Study of difficult engineering concepts, the development and validation of concept inventories as cognitive diagnostic instruments, and the effect of culture and language on Hispanic engineering students’ understanding the fundamental concepts.*


+ ***Research Assistant*** \| SMART Program, University of Colorado, Boulder \| **Summer 2012** \|

    Research Project: Centrifuge Testing to Evaluate Seismic Lateral Earth Pressures on Buried Reservoirs | Emphasis: Geotechnical Engineering, Earthquake Engineering, Faculty Mentor: Dr. Shideh Dashti
    
    Contributions: Installed a 1-D shake table on the centrifuge platform to simulate earthquake motions in flight. Calibrated instruments and created instructional manuals and videos for each sensor type; Installed instruments and connected to the data acquisition system; Prepared soil models with the dry pluviation method and installed sensors at key locations within the soil and on the structure; Performed preliminary tests on Nevada sand for characterizing its behavior; Performed centrifuge experiments to study soil-structure-interaction effects near a buried reservoir under a range of input.


******************************
**PROFESSIONAL & LEADERSHIP**



+ ***Wind Energy Fellows Program Coordinator*** \| University of Massachusetts Amherst \| **Jan 2021 – Jan 2025** \|

    + Coordinate seminar series, poster session, outreach events on the Wind Energy Fellows
    + Assist in the Wind Energy Fellow class
    + Manage budget and prepare reports and Work with the WEF web person to keep the website up to date

+ ***Strategic Analyst Graduate Intern – Materials Science Division*** \| Lawrence Livermore National Laboratory, Livermore CA \| **May 2022 – Aug 2022** \|

    + Support Strategic Analysis for DOE’s Advanced Manufacturing Office in the area of water treatment and water resource recovery technologies
    + Apply “learning curve analysis” and “experience rates” to project development and adoption trajectories for advanced water treatment systems
    + Gather and analyze data and information in support of scientific research, and Participate in research planning and evaluation discussions
    + Prepare end-of-assignment technical report


+ ***Strategic Analyst Graduate Intern – Atmospheric, Earth & Energy*** \| Lawrence Livermore National Laboratory, Livermore CA \| **May 2021 – Aug 2021** \|

    + Support Strategic Analysis for DOE’s Advanced Manufacturing Office in the area of water treatment and water resource recovery technologies
    Apply “learning curve analysis” and “experience rates” to project development and adoption trajectories for advanced water treatment systems
    + Gather and analyze data and information in support of scientific research, and participate in research planning and evaluation discussions
    + Prepare end-of assignment technical report



+ ***Strategic Analyst Graduate Intern – Research Support Facility*** \| National Renewable Energy Laboratory, Golden Colorado \| **Mar 2019 – Aug 2019** \| 

    + Support Strategic Analysis in determining learning and experience rates across manufacturing, fossil energy (including fuels), renewable energy (including bioenergy and biofuels), food processing, petrochemicals, and related industries
    + Conduct objective research that generates independent, high quality, and reproducible results.
    + Support research into industrial learning of industries analogous to advanced biofuels
    
+ ***Project Manager*** \| Ingenium Professional Group PSC \| **Summer 2018**

    + Damage Assessment of Schools in Puerto Rico caused by the Hurricane Maria

+ ***Civil/Environmental Engineering Intern*** \| Tetra Tech inc., Water Resources & Environmental Compliance \| **Fall 2015** \|

    *Provided support to the Tetra Tech Water Resources and Environmental Compliance Manager, specifically on EPA Industrial and Municipal Strom Water Program compliance tasks. Some of the duties: (1) Developed Storm Water Sewer System Maps, (2) Conducted outfall reconnaissance inventory, (3) Conducted Dry Weather Inspections, (4) Developed GIS figures, (5) Developed Spill Prevention, Control and Countermeasure Plan, (6) Conducted field inspections and prepared reports for Hazard Mitigation Projects)*
    

## Research papers
**Articles Published**

+ **Hernandez-Negron, C. G.**, Baker, E., & Goldstein, A. P. (2023). [*A hypothesis for experience curves of related technologies with an application to wind energy.*](https://www.sciencedirect.com/science/article/abs/pii/S1364032123003490?via%3Dihub) Renewable and Sustainable Energy Reviews, 184, 113492.https://doi.org/10.1016/j.rser.2023.113492

+ Papadopoulos, C., Santiago-Roman, A.I., Portela-Gauthier, G., Oquendo, E. F., Candelario Suarez, D., **Hernandez-Negron, C. G.**, Perez-Vargas, M. J. (2015, June),[*Evidence of Learning Gains in Statics as a Result of Simulation-based Instruction*](https://peer.asee.org/evidence-of-learning-gains-in-statics-as-a-result-of-simulation-based-instruction) Paper presented at 2015 ASEE Annual Conference & Exposition, Seattle, Washington. 10.18260/p.24034



## Work papers in progress

+ Hernandez-Negron C. G. and Baker E., Exploring metrics in learning curves: An application to water recycling Understanding the evolution of water recycling– Work in Progress 

+ Hernandez-Negron C. G. and Baker E.. Disaggregating Errors in Forecasts of Technological Change – Work in Progress 

